embeddings {
tensor_name: "train:00000"
tensor_path: "00000/train/tensors.tsv"
metadata_path: "00000/train/metadata.tsv"
}
embeddings {
tensor_name: "test:00000"
tensor_path: "00000/test/tensors.tsv"
metadata_path: "00000/test/metadata.tsv"
}
